### ISSUE TITLE
Button slider 

### ISSUE THREAD

**Issue by benmiaou** [benmiaou/chatluthier#5]
![Screenshot 2024-04-16 at 14 09 12](https://github.com/benmiaou/chatluthier/assets/10078003/29027e82-7b73-4252-bbd3-60e5315f4090)

0% sound not playing 
slide the button to increase volume

**Comment by GuillaumeGwigwi** [comment]
We might also do some "+" "-" sound management system with a 1 -> 10 volume level ?

I am not sure about the 1 -> 100 with steps of 1 mechanism

what you think ?

**Comment by benmiaou** [comment]
Yes go for 10 steps, 100 is way too much
