### ISSUE TITLE
Background random playlist 

### ISSUE THREAD

**Issue by benmiaou** [benmiaou/chatluthier#8]
Make the background music create a list of files to read in a random order and repeat the list when over

**Comment by GuillaumeGwigwi** [comment]
It is kind of linked to #7 isn't it ?

**Comment by benmiaou** [comment]
no, in the code now the files are red randomly so a gile can be read 2 times, the goal of the issue is to change this behaviour to get all the files make a random playlist and read it in loop

**Comment by GuillaumeGwigwi** [comment]
Okay, got it
